name: SonarQube Analysis

on:
  push:
    branches:
      - main  # O cualquier otra rama principal que uses
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Cache SonarQube dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de SonarQube como secreto
      run: |
        # Si no tienes el sonar-scanner instalado, puedes instalarlo con npm o ejecutarlo directamente
        npm install -g sonar-scanner
        sonar-scanner -Dsonar.projectKey=InclusiveAI \
                       -Dsonar.projectName=InclusiveAI \
                       -Dsonar.host.url=http://localhost:9000 \
                       -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Usa el token del secreto de GitHub
